<Project>
  <PropertyGroup>
    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
    <Company>OnlyExo365</Company>
    <Product>OnlyExo365</Product>
    <RuntimeIdentifiers Condition="'$(RuntimeIdentifiers)' == ''">win-x64;win-x86</RuntimeIdentifiers>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
